on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - 'version-*'

jobs:
  tsc-lint:
    container:
      image: node:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm i -g pnpm
    - run: pnpm lint